# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  ansible: orbss/ansible-playbook@0.0.5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

jobs:
  my-job1:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  create-infrastructure:
    docker:
      - image: cimg/aws:2023.04

    steps:
      - checkout
      - run:
          name: "AWS CLI version"
          command: aws --version
      - run:
          name: "Create CloudFormation Stack"
          command: |
            aws cloudformation deploy \
              --template-file servers.yml \
              --stack-name udacityStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  
  configure_infrastructure:
    docker:
      - image: cimg/python:3.11.3
    
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "72:09:b6:da:88:07:87:9e:e9:32:6e:57:1a:0e:b1:4e"
      - run:
          name: Install ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt ansible-main-remote.yml

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy-web-server:
    jobs:
      # - create-infrastructure
      - configure_infrastructure
